# This is a Dockerfile to build an image to help debugging in a debian environment
# Try to keep it close to the CI build for debian in .gitlab-ci
# Run
# docker build \
#    --build-arg=OCAML_VERSION=4.11 \
#    --build-arg=DEBIAN_VERSION=3.14 \
#    -t ocaml-bls12-381-debian \
#    -f utils/Dockerfile-debian \
#    .

ARG OCAML_VERSION

FROM ocaml/opam:debian-ocaml-${OCAML_VERSION}

# Not copying benchmark for the moment. Require to install core_bench
# COPY benchmark/ benchmark/
COPY --chown=opam common/ common/
COPY --chown=opam src/ src/
COPY --chown=opam test/ test/
COPY --chown=opam bls12-381.opam .
COPY --chown=opam bls12-381-unix.opam .
COPY --chown=opam dune-project .

RUN sudo apt-get update
RUN sudo apt-get install gdb strace valgrind -y

# For debugging purpose
RUN sudo apt-get install vim -y

RUN eval $(opam env) && \
  opam update && \
  opam depext -i -y conf-pkg-config conf-libffi && \
  opam depext -i -y zarith && \
  opam install . --deps-only --with-test
