language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
matrix:
  include:
  - env: OCAML_VERSION=4.09
    os: osx
  - env: OCAML_VERSION=4.02
    os: linux
  - env: OCAML_VERSION=4.08
    os: linux
  - env: OCAML_VERSION=4.11
    os: linux
  - env: OCAML_VERSION=4.12
    os: linux
  - env: OCAML_VERSION=4.06 OPAM_SWITCH=4.06.1+32bit
    os: linux
    addons:
      apt:
        packages:
        - gcc-multilib
  - env: OCAML_VERSION=4.10 OPAM_SWITCH=4.10.2+32bit
    os: linux
    addons:
      apt:
        packages:
        - gcc-multilib
